export const HistoryData = [{
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: false,
        price: 2000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 2000,

    },
    {
        Name: "Infection",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 2000,

    },
    {
        Name: "sugar",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 2000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: false,
        price: 2000,
    },
    {
        Name: "cold",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 2000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 2000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: false,
        price: 200,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 1000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: false,
        price: 5000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: true,
        price: 4000,
    },
    {
        Name: "fever",
        hospital_name: "oracle hospital",
        address: "vishram baug near walchand college sangli",
        doctor: "subodh",
        start_date: "10/12/2023",
        end_date: "10 / 12 / 2023 ",
        status: false,
        price: 2300,
    }
]